defaults:
  - _base_
  - _self_
  - override launcher: process

experiment_name: fp16+gptq+exllamav2

backend:
  # for some reason core gets dumped
  # with dummy weights + exllamav2
  no_weights: false
  quantization_scheme: gptq
  quantization_config:
    exllama_config:
      version: 2

hydra:
  sweeper:
    params:
      model: TheBloke/LLaMa-7B-GPTQ,TheBloke/LLaMa-13B-GPTQ
