name: OnnxRuntime Training Unit Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Restore files ownership
        run: docker run
          --rm
          --entrypoint /bin/bash
          --env HOST_UID=`id -u`
          --env HOST_GID=`id -g`
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          ubuntu
          -c 'chown -R ${HOST_UID}:${HOST_GID} /workspace/optimum-benchmark'

      - name: Checkout
        uses: actions/checkout@v2

<<<<<<< HEAD:.github/workflows/test_cuda_onnxruntime_training.yaml
<<<<<<< HEAD:.github/workflows/test_ort_training.yaml
      - name: Build OnnxRuntime Training Docker image
        run: docker build --no-cache --build-arg CACHEBUST=$(date +%s) -f docker/ort_training.dockerfile -t optimum-benchmark-ort-training .

      - name: Run OnnxRuntime Training tests
=======
      - name: Run tests
>>>>>>> seperated backend-device tests and update setup.py:.github/workflows/test_cuda_onnxruntime_training.yaml
=======
      - name: Run tests
>>>>>>> 426195cd6a0486e6594b50a0bb43eedc943aaaaf:.github/workflows/test_ort_training.yaml
        run: docker run
          --rm
          --entrypoint /bin/bash
          --gpus '"device=0,1"'
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          onnxruntime-training
          -c "pip install -e .[test] && pytest -k 'onnxruntime_training' -x"
