name: Pytorch RoCm Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: hf-amd-mi210-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build
          --file docker/rocm.dockerfile
          --build-arg USER_ID=$(id -u)
          --build-arg GROUP_ID=$(id -g)
          --build-arg ROCM_VERSION=5.6.1
          --build-arg UBUNTU_VERSION=22.04
          --tag opt-bench-rocm:5.6.1
          .

      - name: Run tests
        run: docker run
          --rm
          --device /dev/kfd
          --device /dev/dri
          --entrypoint /bin/bash
          --shm-size=64G
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          --env USE_ROCM="1"
          opt-bench-rocm:5.6.1
          -c "pip install -e .[test,peft,diffusers] && pytest -k 'cuda and pytorch' -x"
