name: OnnxRuntime CUDA Training Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: hf-dgx-01
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build
          --file docker/cuda.dockerfile
          --build-arg USER_ID=$(id -u)
          --build-arg GROUP_ID=$(id -g)
          --build-arg CUDA_VERSION=11.8.0
          --build-arg UBUNTU_VERSION=22.04
          --tag opt-bench-cuda:11.8.0-cudnn8
          .

      - name: Run tests
        run: |
          docker run
            -it
            --rm
            --gpus '"device=0,1"'
            --entrypoint /bin/bash
            --volume $(pwd):/workspace/optimum-benchmark
            --workdir /workspace/optimum-benchmark
            --env USE_CUDA="1"
            onnxruntime-training:11.8.0-cudnn8
            -c "pip install -e .[test,peft] && pytest -k 'cuda and onnxruntime and training' -x"
